openapi: 3.0.0
info:
  title: Swagger Free Switch
  version: 1.0.0
servers:
- url: http://localhost:8080/api/v1
tags:
- name: Free switch
  description: Access to Free Switch rules
paths:
  /extensions:
    get:
      summary: Fetch all extensions
      operationId: extensions
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/extensionsResp'
    post:
      summary: Create Extensions
      operationId: extension
      requestBody:
        description: Create extensions
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/extensionsReq'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id
                    example: 2
                  sip_username:
                    type: string
                    description: sip username
                    example: "20005"
                  sip_password:
                    type: string
                    description: sip password
                    example: "1"
                  domain:
                    type: integer
                    description: extenion domain
      x-codegen-request-body-name: body
  /sendsms:
    post:
      summary: Send SMS
      operationId: sendsms
      requestBody:
        description: Send SMS on us number
        content:
          '*/*':
            schema:
              type: object
              properties:
                sms_to:
                  type: string
                  description: sms to
                  example: "15014998137"
                sms_body:
                  type: string
                  description: write body here
                  example: HEY
                callback_url:
                  type: string
                  description: write callback url
                  example: https://webhook.site/da7b7433-e75e-45c1-a81d-d274955b4531
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: id
                    example: 2
                  sms_to:
                    type: string
                    description: enter us number
                    example: "15014998137"
                  sms_body:
                    type: string
                    description: enter sms body
                    example: HEY
                  callback_url:
                    type: string
                    description: domain name
                    example: https://webhook.site/da7b7433-e75e-45c1-a81d-d274955b4531
                  status:
                    type: integer
                    description: status
                    example: 0
      x-codegen-request-body-name: body
  /phonenumber:
    post:
      summary: Add phone number
      operationId: phonenumber
      parameters:
      - name: number
        in: query
        required: true
        schema:
          type: string
      - name: business_name
        in: query
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phonenumberRes'
      security:
      - jwt_token: []
  /numbers/search:
    get:
      summary: Search numbers
      operationId: search-number
      parameters:
      - name: npa
        in: query
        schema:
          type: string
      - name: limit
        in: query
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/didNumberResp'
      security:
      - jwt_token: []
  /numbers:
    get:
      summary: Fetch all numbers
      operationId: numbers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/numbersResp'
      security:
      - jwt_token: []
  /buy-number:
    post:
      summary: Buy phone number
      operationId: buy-number
      requestBody:
        description: Send SMS on us number
        content:
          '*/*':
            schema:
              type: object
              properties:
                phonenumber:
                  type: string
                  description: us phonenumber buy
                  example: "15014998137"
                extension:
                  type: integer
                  description: extension
                  example: 1
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buyNumberResp'
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
  /ivr-calling:
    post:
      summary: IVR calling
      operationId: ivr-calling
      requestBody:
        description: call on US Number
        content:
          '*/*':
            schema:
              type: object
              properties:
                number:
                  type: string
                  description: enter us phone number
                  example: "15014998137"
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ivrCallingResp'
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
  /scan-number:
    post:
      summary: Scan number
      operationId: scan-number
      requestBody:
        description: scan number
        content:
          '*/*':
            schema:
              type: object
              properties:
                limit:
                  type: integer
                  description: limit
                  example: 10
                offset:
                  type: integer
                  description: offset
                  example: 0
                number:
                  type: string
                  description: us number
                  example: "15014998137"
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scanNumberResp'
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
  /call-menu:
    post:
      summary: Call menu
      operationId: call-menu
      requestBody:
        description: call menu
        content:
          '*/*':
            schema:
              type: object
              properties:
                number:
                  type: string
                  description: number
                  example: "15014998137"
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ivrMenuResp'
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
  /call-submenu:
    post:
      summary: Call sub menu
      operationId: call-submenu
      requestBody:
        description: call submenu
        content:
          '*/*':
            schema:
              type: object
              properties:
                forwarding_number:
                  type: string
                  description: forwarding_number
                  example: "15014998137"
                id:
                  type: string
                  description: is
                  example: "28"
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ivrCallingResp'
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
  /sms/callback:
    post:
      summary: SMS callback
      operationId: callback
      requestBody:
        description: SMS callback
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/callBackRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
      security:
      - jwt_token: []
      x-codegen-request-body-name: body
components:
  schemas:
    extensionsResp:
      type: array
      items:
        $ref: '#/components/schemas/extensionResp'
    numbersResp:
      type: array
      items:
        $ref: '#/components/schemas/numberResp'
    scanNumberResp:
      type: object
      properties:
        count:
          type: integer
          description: count
          example: 31
        next:
          type: string
          description: next
          example: https://phoneai.boomslang.io/api/scan/?limit=3&number=&offset=3
        previous:
          type: string
          description: previous
          example: ""
        results:
          type: array
          items:
            $ref: '#/components/schemas/scanNumberResults'
    callBackRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            attributes:
              type: object
              properties:
                body:
                  type: string
                  description: body
                  example: test sms on v23
                level:
                  type: integer
                  description: level
                  example: 2
                status:
                  type: string
                  description: status
                  example: message buffered
                status_code:
                  type: integer
                  description: status code
                  example: 1003
                status_code_description:
                  type: string
                  description: status code description
                  example: Message accepted by Carrier
                timestamp:
                  type: string
                  description: timestamp
                  example: 2017-12-21T16:44:35+00:00
        id:
          type: string
          description: id
          example: mdr2-20858db17d54450295cb059292c8f61f
        links:
          type: object
          properties:
            related:
              type: string
              description: related
              example: https://api.flowroute.com/v2.2/messages/mdr2-39cadeace66e11e7aff806cd7f24ba2d
        type:
          type: string
          description: type
          example: delivery_receipt
    scanNumberResults:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 2
        phone_number:
          type: string
          description: phone number
          example: "1878203086"
        business_name:
          type: string
          description: business name
          example: test
        completed:
          type: string
          description: completed
          example: "true"
        attempt:
          type: string
          description: attempt
          example: "0"
        created_at:
          type: string
          description: Created at
          example: 2022-06-12T07:35:50.947110Z
        updated_at:
          type: string
          description: Created at
          example: 2022-07-12T07:35:50.947110Z
    ivrMenuResp:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 1
        number:
          type: string
          description: number
          example: "1878203086"
        business_name:
          type: string
          description: business_name
          example: phoneapi
        retry_enabled:
          type: integer
          description: retry_enabled
          example: 1
        completed:
          type: boolean
          description: completed
          example: true
        menu:
          type: object
          properties:
            id:
              type: integer
              description: id
              example: 224
            info:
              type: object
              properties:
                parent_text:
                  type: string
                  description: parent_text
                  example: example
                keys_to_reach:
                  type: string
                  description: keys_to_reach
                  example: test
            key:
              type: string
              description: key
              example: ""
            audio_text:
              type: string
              description: audio_text
              example: hello welcome to d. p. software solutions please press one
                for sales press support press 3 for operator
            children:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: id
                    example: 3
                  info:
                    type: object
                    properties:
                      parent_text:
                        type: string
                        description: parent_text
                        example: example
                      keys_to_reach:
                        type: string
                        description: keys_to_reach
                        example: test
                  key:
                    type: string
                    description: key
                    example: "1"
                  audio_text:
                    type: string
                    description: audio_text
                    example: thanks for contact sales department please press 3 to
                      voice yes and press 5 for facts
    numberResp:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 2
        provider:
          type: integer
          description: provider
          example: 2
        phonenumber:
          type: string
          description: phone number
          example: "15014998137"
        domain:
          type: string
          description: domain
          example: phoneai.boomslang.io
        extension:
          type: integer
          description: extension
          example: 1
        created_at:
          type: string
          description: Created at
          example: 2022-06-12T07:35:50.947110Z
    phonenumberRes:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 2
        number:
          type: string
          description: sip username
          example: "15014998137"
        business_name:
          type: string
          description: business name
          example: test
        created_at:
          type: string
          description: created time
          example: 2022-06-17T09:28:12.888225Z
        updated_at:
          type: string
          description: updated time
          example: 2022-06-17T09:31:43.488577Z
    didNumberResp:
      type: object
      properties:
        data:
          type: array
          description: numbers array
          items:
            $ref: '#/components/schemas/didNumber'
    didNumber:
      type: object
      properties:
        number:
          type: string
          description: sip username
          example: "15014998137"
        monthly_cost:
          type: integer
          description: monthly cost
    extensionResp:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 2
        sip_username:
          type: string
          description: sip username
          example: "20005"
        sip_password:
          type: string
          description: sip password
          example: 321d34d3
        domain:
          type: string
          description: domain
          example: phoneai.boomslang.io
    ivrCallingResp:
      type: object
      properties:
        dial_number:
          type: string
          description: dial number
          example: "15014998137"
        status:
          type: string
          description: status
          example: success
        call_uuid:
          type: string
          description: call uuid
          example: 5cfc64e2-859f-4ff3-8a5e-734e4a1d547a
        message:
          type: string
          description: message
          example: message
        fs_output:
          type: string
          description: fs output
          example: |
            +OK Job-UUID: 2c973a36-f05b-11ec-a2c2-a593d3cd889e
    extensionsReq:
      type: object
      properties:
        sip_username:
          type: string
          example: sip
        sip_password:
          type: string
          example: test@123
    buyNumberResp:
      type: object
      properties:
        sip_username:
          type: string
          example: testusername
        sip_password:
          type: string
          example: testuserpass
  parameters:
    keyword:
      name: keyword
      in: query
      required: true
      schema:
        type: string
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: integer
    npa:
      name: npa
      in: query
      schema:
        type: string
    business_name:
      name: business_name
      in: query
      schema:
        type: string
    number:
      name: number
      in: query
      required: true
      schema:
        type: string
  securitySchemes:
    jwt_token:
      type: apiKey
      name: Token
      in: header
